"""Cluster-level price trend analysis."""
def build_cluster_series(df, cluster_col, freq="MS"):
    """Median log price-per-sqft per cluster per month; flag thin months."""
def decompose(series, model="additive"): ...
def adf_test(series): """Return statistic, p-value, lags, verdict at alpha."""
def fit_arima(series, order=None): ...
def fit_prophet(series): ...
def backtest(series, horizon, n_folds=3): """rolling-origin, report MAPE/RMSE"""
